# Generated by Django 5.2.7 on 2025-10-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customeruser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
