# Generated by Django 5.2.7 on 2025-10-29 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customeruser_auth_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
